# Generated by Django 5.0.4 on 2024-04-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_user_bot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bot',
            new_name='Employees',
        ),
    ]
